# author: Nick Gerzen
#
# Entry point of entire installation and setup process. It installs a base Arch Linux system and configures
# it to special needs.

---
- name: bootstrap base system
  hosts: device
  gather_facts: yes
  user: root
  tasks:

    name: setting the new hostname
    hostname:
      name: "ansssss"
