# author: Nick Gerzen
#
# Entry point of entire installation and setup process. It installs a base Arch Linux system and configures
# it to special needs.
---
- name: bootstrap base system
  hosts: target_device
  user: root
  tasks:

    - include_role:
        name: partitioning_and_encryption

    - name: install base system via pacstrap
      command: "/usr/bin/pacstrap {{ mount_point }} base linux linux-firmware lvm2 inetutils grub vim openssh networkmanager man-db man-pages"

    - include_role:
        name: setup_base_system

    - include_role:
        name: install_grub
