# author: Nick Gerzen
#
# Entry point of entire installation and setup process. It installs a base Arch Linux system and configures
# it to special needs.

---
- name: bootstrap base system
  hosts: localhost
  user: root
  tasks:

    - name: partitioning - create bios/gpt boot partition
      parted:
        device: "{{ target_device_id }}"
        label: gpt
        name: boot
        number: 1
        part_start: "0%"
        part_end: '{{ boot_part_size }}'
        unit: "MiB"
        state: present

    - name: partitioning - create primary partition
      parted:
        device: "{{ target_device_id }}"
        label: gpt
        name: root
        number: 2
        part_start: '{{ boot_part_size }}'
        part_end: "100%"
        unit: "MiB"
        state: present

    - name: encryption - create and open luks container
      luks_device:
        device: "{{ luks_partition_path }}"
        state: opened
        passphrase: "{{ luks_passphrase }}"
        name: "{{ luks_name }}"
        type: luks2

    - name: lvm - create volume group on LUKS container
      lvg:
        pvs: "/dev/mapper/{{ luks_name }}"
        vg: "{{ volume_group }}"
        state: present

    - name: lvm - create logical volume for swap
      lvol:
        vg: "{{ volume_group }}"
        lv: "{{ lv_swap }}"
        size: "{{ lv_swap_size }}"
        state: present

    - name: lvm - create logical volume for /root
      lvol:
        vg: "{{ volume_group}}"
        lv: "{{ lv_root }}"
        size: "{{ lv_root_size }}"
        state: present

    - name: lvm - create logical volume for /home
      lvol:
        vg: "{{ volume_group }}"
        lv: "{{ lv_home }}"
        size: 100%FREE
        shrink: no
        state: present

    - name: formatting - create swap
      filesystem:
        dev: "/dev/{{ volume_group }}/{{ lv_swap }}"
        fstype: swap
        state: present

    - name: formatting - create ext4 on /root
      filesystem:
        dev: "/dev/{{ volume_group }}/{{ lv_root }}"
        fstype: ext4
        state: present

    - name: formatting - create ext4 on /home
      filesystem:
        dev: "/dev/{{ volume_group }}/{{ lv_home }}"
        fstype: ext4
        state: present

    - name: mount lv root to /mnt
      mount:
        path: /mnt
        src: "/dev/mapper/{{ lv_root }}"
        fstype: ext4
        state: mounted

    - name: install base system via pacstrap
      command: /usr/bin/pacstrap /mnt base linux linux-firmware
      register: output
