# author: Nick Gerzen
#
# Entry point of entire installation and setup process. It installs a base Arch Linux system and configures
# it to special needs.
---
- name: bootstrap base system
  hosts: target_device
  user: root
  tasks:

    - include_role:
        name: partitioning_and_encryption
        #vars:
        #  mount_point: "{{ mount_point }}"

    - name: install base system via pacstrap
      command: "/usr/bin/pacstrap {{ mount_point }} base linux linux-firmware lvm2 grub vim openssh networkmanager man-db man-pages"

    - include_role:
        name: setup_base_system
        #  vars:
        #    mount_point: "{{ mount_point }}"

      #    - name: set timezone
      #      file:
      #        src: "{{ timezone }}"
      #        state: link
      #        mode: 0777
      #        force: yes
      #
      #    - name: set hwclock to UTC
      #      timezone:
      #        hwclock: UTC
      #
      #    - name: generate /etc/adjtime
      #      command: /usr/bin/hwlock --systohc
      #
      #    - name: generate locales
      #      locale_gen:
      #        name: en_US.UTF-8
      #        state: present
      #
      #    - name: verify keyboard layout
      #      lineinfile:
      #        path: /etc/vconsole.conf
      #        line: "{{ keyboard_layout}}"
      #        create: yes
      #        mode: 0644
      #        owner: root
      #        state: present
      #
      #    - name: set hostname
      #      hostname:
      #        name: "{{ hostname }}"
      #
      #    - name: vefify lvm2 package is installed
      #      pacman:
      #        name: lvm2
      #        state: present
      #
      #    - name: insert hooks for new initramfs
      #      lineinfile:
      #        path: /etc/mkinitcpio.conf
      #        regex: '^HOOKS=(.*)'
      #        #line: 'HOOKS=(base udev autodetect modconf block encrypt lvm2 filesystems keyboard fsck)'
      #        line: 'HOOKS=(base udev autodetect keyboard keymap consolefont modconf block encrypt lvm2 filesystems fsck)'
      #        mode: 0644
      #        owner: root
      #        state: present
      #
      #    - name: generate new initramfs
      #      command: /usr/bin/mkinitcpio -P
      #
      #    - name: vefify grub package is installed
      #      pacman:
      #        name: grub
      #        state: present
      #
      #    - name: install grub
      #      command: "/usr/bin/grub-install --target=i386-pc {{ target_device_path }}"
      #
      #    - name: configure grub
      #      lineinfile:
      #        path: /etc/default/grub
      #        regex: '^GRUB_CMDLINE_LINUX_DEFAULT='
      #        line: 'cryptdevice=/dev/{{ volume_group }}/{{ lv_root }}:cryptroot root=/dev/{{ volume_group }}/{{ lv_root }}'
      #        state: present
      #
      #    - name: generate grub config
      #      command: grub-mkconfig -o /boot/grub/grub.cfg
