# author: Nick Gerzen
#
# Entry point of entire installation and setup process. It installs a base Arch Linux system and configures
# it to special needs.

---
- name: bootstrap base system
  hosts: localhost
  user: root
  tasks:

    - name: create and open luks container
      luks_device:
        device: "{{ luks_partition }}"
        state: opened
        passphrase: "{{ luks_passphrase }}"
        name: "{{ luks_name }}"
        type: luks2

    - name: create volume group on LUKS container
      lvg:
        pvs: "/dev/mapper/{{ luks_name }}"
        vg: "{{ volume_group }}"
        state: present

    - name: create logical volume for /boot
      lvol:
        vg: "{{ volume_group }}"
        lv: "{{ lv_boot }}"
        size: "{{ lv_boot_size }}"
        state: present

    - name: create logical volume for /swap
      lvol:
        vg: "{{ volume_group }}"
        lv: "{{ lv_swap }}"
        size: "{{ lv_swap_size }}"
        state: present

    - name: create logical volume for /home
      lvol:
        vg: "{{ volume_group }}"
        lv: "{{ lv_home }}"
        size: "{{ lv_home_size }}"
        state: present

    - name: create logical volume for /root with remaining size
      lvol:
        vg: "{{ volume_group}}"
        lv: "{{ lv_root }}"
        size: 100%FREE
        state: present

    - name: create ext4 on /root
      filesystem:
        dev: "/dev/{{ volume_group }}/{{ lv_root }}"
        fstype: ext4
        state: present

    - name: create ext4 on /home
      filesystem:
        dev: "/dev/{{ volume_group }}/{{ lv_home }}"
        fstype: ext4
        state: present

    - name: create swap
      filesystem:
        dev: "/dev/{{ volume_group }}/{{ lv_swap }}"
        fstype: swap
        state: present

